In [7]:
import pandas as pd
from faker import Faker

In [8]:
# Create a Faker object
fake = Faker()

In [11]:
def generate_data(num_records):
    return pd.DataFrame(
        {
            'Name': [fake.name() for _ in range(num_records)],
            'Email': [fake.email() for _ in range(num_records)],
            'Address': [fake.address() for _ in range(num_records)],
            'PhoneNumber': [fake.phone_number() for _ in range(num_records)],
            'Country': [fake.country() for _ in range(num_records)],
            'Latitude': [fake.latitude() for _ in range(num_records)],
            'Longitude': [fake.longitude() for _ in range(num_records)],
            'DateofBirth': [fake.date_of_birth(minimum_age=18, maximum_age=90) for _ in range(num_records)],
            'Company': [fake.company() for _ in range(num_records)],
            'Job': [fake.job() for _ in range(num_records)],
            'CreditCardNumber': [fake.credit_card_number() for _ in range(num_records)],
            'ExpirationDate': [fake.credit_card_expire() for _ in range(num_records)],
        }
    )

In [12]:
generate_data(10)

,Name,Email,Address,PhoneNumber,Country,Latitude,Longitude,DateofBirth,Company,Job,CreditCardNumber,ExpirationDate
0,Thomas Graham,dramos@example.net,"131 Ryan Forge Suite 892\nJefferyfort, MI 10104",614.838.3599x637,Azerbaijan,27.1605725,-96.316329,1991-06-14,Gonzalez-Cain,Medical sales representative,3589413899411522,01/28
1,Jonathan Love,mary91@example.com,"20141 Wade Center Suite 070\nNew Travis, WY 52977",(739)160-5028,Peru,87.8345175,-26.320180,1937-10-24,"Collier, Harmon and Curtis","Nurse, mental health",5329737222534893,04/33
2,Brian Kennedy,lrush@example.org,"5686 Leah Isle Suite 716\nLake Teresaton, NV 9...",455-952-3044x39344,Senegal,-66.851002,127.975861,1934-12-04,Brooks PLC,Equality and diversity officer,3508554979684047,04/33
3,Tyler Riley MD,vschwartz@example.com,"81584 Crystal Mountains\nSouth Carriemouth, PR...",591-006-5486x498,Bhutan,83.4028805,139.157452,1974-11-05,"Martinez, Jacobs and Watson","Buyer, industrial",4248483064049804,06/32
4,Garrett Jackson,kyleparker@example.com,"6224 Robin Extensions\nMichelletown, MP 94480",979.242.7978x686,Tajikistan,64.941134,-30.911368,1952-03-23,"Olsen, Taylor and Johnson",IT trainer,213180641023463,07/29
5,Brett King,hallwilliam@example.org,"12509 Nichole Crest\nLake Michael, AK 47368",935.240.5158x54946,Chad,-28.354164,22.722409,1934-06-20,Jones-Chaney,Chief Executive Officer,3590704582439557,02/27
6,Danielle Long,audrey08@example.com,Unit 7397 Box 5997\nDPO AE 72964,(688)312-6822x09989,Turkey,-75.9096335,-96.044538,1950-02-08,Graham-Shaw,Adult nurse,6011082758882858,07/32
7,Phillip Lewis,gallowayshannon@example.net,USCGC White\nFPO AP 50027,633.015.2811x15605,Cocos (Keeling) Islands,47.8069885,19.213778,1944-03-08,"Greene, Chung and Hernandez","Librarian, public",4283080901323,12/30
8,Lori Young,rodneyrush@example.net,"293 Webb Manor\nNorth Jessica, PR 71021",+1-101-826-7530,Guadeloupe,-7.629188,86.037288,1949-12-05,Warren-Rogers,Estate manager/land agent,4942493842144215165,08/25
9,Christy Watkins,vasquezcharles@example.com,"1680 Boyd Manors\nFryeport, VA 52482",6738115594,Cambodia,-35.340274,-101.030129,1995-08-05,Cunningham-Holloway,Architectural technologist,639071280270,08/26

In [13]:
generate_data(20)

,Name,Email,Address,PhoneNumber,Country,Latitude,Longitude,DateofBirth,Company,Job,CreditCardNumber,ExpirationDate
0,Jon Simmons,andrewmaldonado@example.org,"8907 Meza Highway Suite 817\nNorth Laurabury, ...",001-152-571-4706x17704,Iceland,-11.039914,153.931072,1997-01-09,Fisher-King,Trading standards officer,4319823950730528099,11/33
1,Samantha Ford,ataylor@example.org,USNV Walters\nFPO AP 59218,517-549-6345x78012,Hungary,58.186711,154.294517,1943-10-24,Chambers-Brown,Dispensing optician,6599711252615840,10/25
2,Devin Kim,james69@example.net,"2560 Vaughn River\nNorth Marc, RI 28794",001-378-215-0511x0961,Serbia,54.739192,-102.629235,1946-07-02,Gonzales-Thompson,"Scientist, physiological",4486162168962263063,02/27
3,Brittany Mitchell,deborah12@example.org,Unit 8539 Box 7779\nDPO AP 91814,(277)212-3961,Norfolk Island,32.0434455,-43.613494,1989-11-23,Thompson-Smith,"Geologist, engineering",4634497348635632586,04/28
4,Patrick Griffith,jonessteven@example.com,"35298 Daniels Skyway Apt. 861\nGordonstad, LA ...",835.085.6315x36836,Mongolia,-15.285287,-47.844370,1984-12-06,George LLC,Air traffic controller,587829364872,11/29
5,Stacy Donovan,jennifer44@example.com,"4998 Anthony Canyon\nBrandonview, LA 03845",455.064.2238,Trinidad and Tobago,-43.446412,72.887379,1936-10-01,Brown-Osborne,Personal assistant,30354498350789,08/24
6,Daniel Williams,burnsamber@example.com,"1286 Ryan Street\nLake Loriberg, PA 59467",(734)693-2884,Samoa,82.1689645,-128.529538,1963-01-02,Webb-Johnston,TEFL teacher,4908246972848,03/31
7,Michael Marshall,jeremyvazquez@example.com,"707 Dennis Court Apt. 304\nWest Cathymouth, MA...",001-212-778-1046,Wallis and Futuna,71.4286585,31.265412,1953-04-28,Martin-Foley,Pension scheme manager,213168875377044,08/31
8,Jeffrey Walker,dianawhite@example.org,"38149 Michelle Hills\nMurphyport, VI 61421",(835)971-1478x894,Svalbard & Jan Mayen Islands,19.8658665,-76.292211,1948-06-01,Franklin-Kelley,"Surveyor, insurance",3549075850669445,06/29
9,Jacqueline Mendez,sarahthomas@example.net,"2603 Anthony Squares\nNew Brettside, WI 81679",3146552182,Ukraine,-34.014158,-122.065246,1954-01-15,Chan LLC,Research scientist (maths),6011786848504427,08/28
10,Scott Jacobs,heather00@example.com,"38531 Webb Ways\nEast Donnafort, PW 48618",(099)594-8929x915,Maldives,-41.5395535,-155.636253,1971-05-23,Erickson-Nguyen,Art gallery manager,4732270624957953775,02/33
11,Christian Maddox,karenmarquez@example.net,"72590 Frazier Lodge\nPort Shane, MO 62390",001-467-428-3410x55425,Norway,78.2728475,129.736519,1953-01-09,Sullivan LLC,Magazine journalist,2272174012802484,06/27
12,Jessica Sharp,ovang@example.net,"95243 Kelly Hill Apt. 899\nOrtizside, NJ 40751",5673890881,Northern Mariana Islands,-33.749372,-28.928452,1949-12-22,"Hardy, Tran and Wang",Clinical cytogeneticist,346932525788664,02/30
13,Michael Lopez,whuffman@example.net,"6770 Olivia Wells\nGilbertport, NY 17521",+1-766-826-4154x07374,Iceland,1.301437,73.024587,1945-11-11,"Ball, Chan and Morales",Gaffer,4041551854447146,08/29
14,Patricia Cooper,murraygerald@example.net,"5911 Wilkinson Points\nMarieshire, RI 02911",(333)205-7637x312,Belize,3.485893,-142.293354,1985-04-21,Williams LLC,Advertising account planner,6011156548721376,02/31
15,Shaun Miller,debbie37@example.com,Unit 8836 Box 9840\nDPO AA 76820,(550)272-8934,France,23.415542,108.211341,1936-03-10,"Robinson, Carter and Morton",Pharmacologist,4437896422445318,09/25
16,Rebecca Conley,wrobinson@example.com,"PSC 7342, Box 7397\nAPO AE 43195",(188)121-7007,Congo,-18.330491,54.076264,1994-08-06,"Mcdonald, Jimenez and Anderson",Higher education lecturer,568889127946,04/25
17,Dana Robbins,carterrichard@example.org,"87906 Hubbard Street\nPhillipsville, SC 81557",001-258-680-0728x70942,Bangladesh,-83.8946105,62.334699,2002-06-26,Wilson and Sons,Firefighter,569512516042,07/24
18,Kelly Robinson,zphillips@example.net,"PSC 8550, Box 6042\nAPO AP 30576",+1-856-009-0468x85709,Ethiopia,62.135106,-32.135432,1986-01-16,Campbell-Banks,"Producer, television/film/video",4588817490337,06/24
19,Justin Mcknight,newmanpatricia@example.org,"83128 Gabriella Coves\nSmithmouth, TX 96863",6228520065,Bhutan,54.579982,121.451301,2004-01-21,Randall Ltd,"Engineer, drilling",570691460119,08/29

In [14]:
# Save DataFrame to a CSV file
generate_data(100).to_csv('fake_data.csv', index=False)

In [15]:
# Save DataFrame to an Excel file
generate_data(200).to_excel('fake_data.xlsx', index=False)

In [16]:
# Save DataFrame to a JSON file
generate_data(10).to_json('fake_data.json', orient='records')